### ISSUE TITLE
Donate QWOYN tokens to Ping.Pub

### ISSUE THREAD

**Issue by dpdanpittman** [ping-pub/ping.pub#24]
Hello,

How do I donate QWOYN tokens to your project?  We really appreciate everything you do and want to send you some tokens.  Can you provide me with a QWOYN address?

Thanks,

Daniel Pittman - Founder
Qwoyn Studios S LLC

**Comment by liangping** [comment]
Thanks. Please update your PR first.

**Comment by liangping** [comment]
Hey @dpdanpittman , This is my address `qwoyn1jxv0u20scum4trha72c7ltfgfqef6nsc0243nw`

thanks for your donation

**Comment by dpdanpittman** [comment]
@liangping sent!
