### ISSUE TITLE
Chains in testnet is not show in dashboard

### ISSUE THREAD

**Issue by anonid-top** [ping-pub/ping.pub#71]
When i add chains in *testnet* directory it not show in **Ping Dashboard**. But i copy that chain files to *mainnet* directory, it show in ***Dashboard***
Please check this error. Thank you.

**Comment by liangping** [comment]
Deploy the explorer to  `testnet.abc.com`

Testnet mode only be activated on domain with prefix 'testnet.'

**Comment by liangping** [comment]
it shows on https://testnet.ping.pub

**Comment by anonid-top** [comment]
Please delete this issue. Thank you!
